services:
  tarantool1:
    image: tarantool/tarantool:2.11 # 3.0 invalid credentials
    environment:
      TARANTOOL_USER_NAME: "user"
      TARANTOOL_USER_PASSWORD: "password"
      TT_READAHEAD: '1632000' # 10x
      TT_VINYL_MEMORY: '2684354560' # 20x
      TT_VINYL_CACHE: '2684354560' # 20x
      TT_NET_MSG_MAX: '76800' # 100x
      TT_MEMTX_MEMORY: '268435456' # 1x
      TT_VINYL_PAGE_SIZE: '8192' # 1x
    ports:
      - "3301:3301"
